/* patients.html 页面脚本（依赖 boot.js → data.js → common.js） */
"use strict";shell('patients');
let state=loadListState('patients',{q:'',status:'',data:'',page:1,perPage:8});
const selected=new Set();

function patientListSkeleton(){
  $('#patient-summary').innerHTML='<span class="skeleton skeleton-inline-summary"></span>';
  $('#patients').innerHTML=Array.from({length:6},()=>`<div class="patient-card selectable patient-skeleton-row"><span class="check-col"><i class="skeleton skeleton-check"></i></span><div class="patient-card-link">${Array.from({length:5},(_,i)=>`<span class="patient-skeleton-cell"><i class="skeleton ${i===0?'skeleton-patient-name':'skeleton-cell-line'}"></i><i class="skeleton skeleton-cell-sub"></i></span>`).join('')}<i class="skeleton skeleton-chevron"></i></div></div>`).join('');
  $('#result-count').innerHTML='<span class="skeleton skeleton-result-count"></span>';
  $('#pagination').innerHTML='';
}
function loadPatients(callback){patientListSkeleton();setTimeout(callback,420)}

const dataMatches=p=>!state.data||(state.data==='missing'?!!p.incomplete:!p.incomplete);
const statusMatches=p=>!state.status||({ongoing:!p.lost&&!p.due&&p.visits>0,due:p.due&&!p.lost,none:p.visits===0,lost:p.lost}[state.status]);
function comorbidCell(p){const cs=comorbidCodes(p);return cs.length?`<span class="comorbid-chips">${cs.map(c=>`<span class="comorbid-chip" role="button" tabindex="0" data-comorbid="${c}" data-pid="${escapeHTML(p.id)}" title="查看${COMORBIDITY_INFO[c].name}病程简要">${c} ${COMORBIDITY_INFO[c].name}</span>`).join('')}</span>`:'<span class="comorbid-none">无</span>'}
function card(p){const s=followupStatus(p);return `<div class="patient-card selectable" data-id="${escapeHTML(p.id)}"><span class="check-col"><input class="patient-check" type="checkbox" value="${escapeHTML(p.id)}" aria-label="选择患者 ${escapeHTML(p.name)}" ${selected.has(p.id)?'checked':''}></span><a class="patient-card-link" href="patient-visits.html?id=${encodeURIComponent(p.id)}"><span class="patient-identity"><span class="record-icon">${icon('record')}</span><span class="patient-info"><span class="patient-name">${escapeHTML(p.name)}${p.incomplete?badge('待补全','warning'):''}</span><span class="patient-meta">${escapeHTML(p.sex)} · ${p.year} 年</span><span class="patient-meta">ID号: ${escapeHTML(p.id)}</span></span></span><span class="patient-cell research-cell"><span class="cell-label">研究信息</span><span class="study-code">${escapeHTML(p.code)}</span><span class="cell-note">已随访 ${p.visits} 次 · ${cycleLabel(p.followCycle)}</span></span><span class="patient-cell disease-cell"><span class="cell-label">疾病资料</span><span>${p.subtype?badge(p.subtype):'<span class="missing-value">分型未提供</span>'}</span><span class="cell-note">${p.das28==null?'DAS28 未提供':`DAS28 ${p.das28}`}</span></span><span class="patient-cell history-cell"><span class="cell-label">其他病史</span>${comorbidCell(p)}</span><span class="patient-cell visit-cell"><span class="cell-label">最近随访</span><span class="last-visit">${icon('calendar')}${p.last||'暂无访视'}</span><span class="cell-note">${p.visits?`累计 ${p.visits} 次访视`:'待完成基线访视'}</span></span><span class="patient-cell status-cell"><span class="cell-label">随访状态</span>${badge(s.label,s.tone)}</span>${icon('chevron','chevron')}</a></div>`}
function visibleRows(){const rows=patients.filter(p=>(!state.q||[p.name,p.id,p.code].some(x=>x.toLowerCase().includes(state.q)))&&statusMatches(p)&&dataMatches(p));return {rows}}
function updateSelectionUI(pageRows=[]){const n=selected.size;const b=$('#ai-analysis');b.disabled=!n;b.textContent=n?`AI智能分析（已选 ${n} 人）`:'AI智能分析';const all=$('#select-all');if(all){const checked=pageRows.filter(p=>selected.has(p.id)).length;all.checked=pageRows.length>0&&checked===pageRows.length;all.indeterminate=checked>0&&checked<pageRows.length}}
function render(){saveListState('patients',state);const {rows}=visibleRows();const pages=Math.max(1,Math.ceil(rows.length/state.perPage));state.page=Math.min(state.page,pages);const start=(state.page-1)*state.perPage;const pageRows=rows.slice(start,start+state.perPage);$('#patient-summary').innerHTML=`共 ${patients.length} 位患者已建档 · <button type="button" class="summary-link" id="show-incomplete" title="筛选资料待补全的患者">${patients.filter(p=>p.incomplete).length}</button> 位资料待补全`;$('#patients').innerHTML=pageRows.map(card).join('');$('#empty').hidden=!!rows.length;$('#result-count').textContent=rows.length?`显示第 ${start+1}–${Math.min(start+state.perPage,rows.length)} 条，共 ${rows.length} 条`:'共 0 条匹配记录';$('#pagination').innerHTML=Array.from({length:pages},(_,i)=>`<button data-page="${i+1}" class="${i+1===state.page?'active':''}">${i+1}</button>`).slice(Math.max(0,state.page-3),Math.max(5,state.page+2)).join('');updateSelectionUI(pageRows)}
const chipOpen=e=>{const c=e.target.closest('.comorbid-chip');if(!c)return false;e.preventDefault();e.stopPropagation();openComorbidity(c.dataset.comorbid,patientById(c.dataset.pid));return true};
$('#patients').addEventListener('click',chipOpen);
$('#patients').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.comorbid-chip'))chipOpen(e)});
$('#patients').addEventListener('change',e=>{if(!e.target.matches('.patient-check'))return;e.target.checked?selected.add(e.target.value):selected.delete(e.target.value);render()});
$('#select-all').addEventListener('change',e=>{const {rows}=visibleRows();const start=(state.page-1)*state.perPage;rows.slice(start,start+state.perPage).forEach(p=>e.target.checked?selected.add(p.id):selected.delete(p.id));render()});
// 数据导出：勾选了患者则导出所选，否则导出当前筛选结果（前端演示 CSV，真实导出需后端接口）
function exportPatients(){const list=selected.size?patients.filter(p=>selected.has(p.id)):visibleRows().rows;if(!list.length){alert('当前没有可导出的患者数据');return}
 const cols=[['ID号','id'],['姓名','name'],['性别','sex'],['出生年份','year'],['研究编号','code'],['分型','subtype'],['DAS28','das28'],['随访次数','visits'],['最近随访','last'],['随访周期(月)','followCycle']];
 const cell=v=>{v=v==null?'':String(v);return /[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v};
 const rows=list.map(p=>[...cols.map(c=>cell(p[c[1]])),cell(comorbidCodes(p).map(c=>c+' '+COMORBIDITY_INFO[c].name).join('；')||'无'),cell(followupStatus(p).label),p.incomplete?'数据缺失':'数据完整'].join(','));
 const csv='\ufeff'+[...cols.map(c=>c[0]),'其他病史','随访状态','数据完整性'].join(',')+'\n'+rows.join('\n');
 const u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=`患者列表-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
$('#ai-analysis').onclick=()=>{if(selected.size)location.href=`ai-cohort.html?ids=${[...selected].map(encodeURIComponent).join(',')}`};
$('#search-form').addEventListener('submit',e=>{e.preventDefault();state.q=$('#query').value.trim().toLowerCase();state.status=$('#visit-status').value;state.data=$('#data-status').value;state.page=1;loadPatients(render)});$('#visit-status').addEventListener('change',e=>{state.status=e.target.value;state.page=1;render()});$('#data-status').addEventListener('change',e=>{state.data=e.target.value;state.page=1;render()});$('#patient-summary').addEventListener('click',e=>{if(!e.target.closest('#show-incomplete'))return;state={...state,q:'',status:'',data:'missing',page:1};$('#query').value='';$('#visit-status').value='';$('#data-status').value='missing';loadPatients(render)});$('#export-data').onclick=exportPatients;$('#pagination').addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b){state.page=+b.dataset.page;render()}});$('#page-size').addEventListener('change',e=>{state.perPage=+e.target.value;state.page=1;render()});$('#reset').onclick=()=>{state={q:'',status:'',data:'',page:1,perPage:state.perPage};$('#query').value='';$('#visit-status').value='';$('#data-status').value='';loadPatients(render)};$('#query').value=state.q;$('#visit-status').value=state.status;$('#data-status').value=state.data;$('#page-size').value=state.perPage;patientListSkeleton();setTimeout(render,520);
