"use strict";shell('patients');
let state={q:'',status:'',filter:'all',page:1,perPage:8};
const selected=new Set();

function patientListSkeleton(){
  $('#patient-summary').innerHTML='<span class="skeleton skeleton-inline-summary"></span>';
  $('#patients').innerHTML=Array.from({length:6},()=>`<div class="patient-card selectable patient-skeleton-row"><span class="check-col"><i class="skeleton skeleton-check"></i></span><div class="patient-card-link">${Array.from({length:5},(_,i)=>`<span class="patient-skeleton-cell"><i class="skeleton ${i===0?'skeleton-patient-name':'skeleton-cell-line'}"></i><i class="skeleton skeleton-cell-sub"></i></span>`).join('')}<i class="skeleton skeleton-chevron"></i></div></div>`).join('');
  $('#result-count').innerHTML='<span class="skeleton skeleton-result-count"></span>';
  $('#pagination').innerHTML='';
}
function loadPatients(callback){patientListSkeleton();setTimeout(callback,420)}

const filters=[['all','全部患者',()=>true],['incomplete','数据待补全',p=>p.incomplete],['due','近期需随访',p=>p.due&&!p.lost],['abnormal','有异常检验',p=>p.abnormal],['lost','已脱落',p=>p.lost]];
const statusMatches=p=>!state.status||({ongoing:!p.lost&&!p.due&&p.visits>0,due:p.due&&!p.lost,none:p.visits===0,lost:p.lost}[state.status]);
function card(p){const s=followupStatus(p);return `<div class="patient-card selectable" data-id="${escapeHTML(p.id)}"><span class="check-col"><input class="patient-check" type="checkbox" value="${escapeHTML(p.id)}" aria-label="选择患者 ${escapeHTML(p.name)}" ${selected.has(p.id)?'checked':''}></span><a class="patient-card-link" href="patient-visits.html?id=${encodeURIComponent(p.id)}"><span class="patient-identity"><span class="record-icon">${icon('record')}</span><span class="patient-info"><span class="patient-name">${escapeHTML(p.name)}${p.incomplete?badge('待补全','warning'):''}</span><span class="patient-meta">${escapeHTML(p.sex)} · ${p.year} 年</span><span class="patient-meta">ID号: ${escapeHTML(p.id)}</span></span></span><span class="patient-cell research-cell"><span class="cell-label">研究信息</span><span class="study-code">${escapeHTML(p.code)}</span><span class="cell-note">已随访 ${p.visits} 次</span></span><span class="patient-cell disease-cell"><span class="cell-label">疾病资料</span><span>${p.subtype?badge(p.subtype):'<span class="missing-value">分型未提供</span>'}</span><span class="cell-note">${p.das28==null?'DAS28 未提供':`DAS28 ${p.das28}`}</span></span><span class="patient-cell visit-cell"><span class="cell-label">最近随访</span><span class="last-visit">${icon('calendar')}${p.last||'暂无访视'}</span><span class="cell-note">${p.visits?`累计 ${p.visits} 次访视`:'待完成基线访视'}</span></span><span class="patient-cell status-cell"><span class="cell-label">随访状态</span>${badge(s.label,s.tone)}</span>${icon('chevron','chevron')}</a></div>`}
function visibleRows(){const base=patients.filter(p=>(!state.q||[p.name,p.id,p.code].some(x=>x.toLowerCase().includes(state.q)))&&statusMatches(p));const f=filters.find(x=>x[0]===state.filter);return {base,rows:base.filter(f[2])}}
function updateSelectionUI(pageRows=[]){const n=selected.size;const b=$('#ai-analysis');b.disabled=!n;b.textContent=n?`AI智能分析（已选 ${n} 人）`:'AI智能分析';const all=$('#select-all');if(all){const checked=pageRows.filter(p=>selected.has(p.id)).length;all.checked=pageRows.length>0&&checked===pageRows.length;all.indeterminate=checked>0&&checked<pageRows.length}}
function render(){const {base,rows}=visibleRows();const f=filters.find(x=>x[0]===state.filter);const pages=Math.max(1,Math.ceil(rows.length/state.perPage));state.page=Math.min(state.page,pages);const start=(state.page-1)*state.perPage;const pageRows=rows.slice(start,start+state.perPage);$('#patient-summary').textContent=`共 ${patients.length} 位患者已建档 · ${patients.filter(p=>p.incomplete).length} 位资料待补全`;$('#filters').innerHTML=filters.map(x=>`<button class="filter-tab ${x[0]===state.filter?'active':''}" data-filter="${x[0]}">${x[1]}<span>${base.filter(x[2]).length}</span></button>`).join('');$('#patients').innerHTML=pageRows.map(card).join('');$('#empty').hidden=!!rows.length;$('#result-count').textContent=rows.length?`显示第 ${start+1}–${Math.min(start+state.perPage,rows.length)} 条，共 ${rows.length} 条`:'共 0 条匹配记录';$('#pagination').innerHTML=Array.from({length:pages},(_,i)=>`<button data-page="${i+1}" class="${i+1===state.page?'active':''}">${i+1}</button>`).slice(Math.max(0,state.page-3),Math.max(5,state.page+2)).join('');updateSelectionUI(pageRows)}
$('#patients').addEventListener('change',e=>{if(!e.target.matches('.patient-check'))return;e.target.checked?selected.add(e.target.value):selected.delete(e.target.value);render()});
$('#select-all').addEventListener('change',e=>{const {rows}=visibleRows();const start=(state.page-1)*state.perPage;rows.slice(start,start+state.perPage).forEach(p=>e.target.checked?selected.add(p.id):selected.delete(p.id));render()});
$('#ai-analysis').onclick=()=>alert(`将对已选择的 ${selected.size} 位患者进行 AI 智能分析。\n（演示交互，后续接入 AI 分析接口）`);
$('#search-form').addEventListener('submit',e=>{e.preventDefault();state.q=$('#query').value.trim().toLowerCase();state.status=$('#visit-status').value;state.page=1;loadPatients(render)});$('#visit-status').addEventListener('change',e=>{state.status=e.target.value;state.page=1;render()});$('#filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(b){state.filter=b.dataset.filter;state.page=1;render()}});$('#pagination').addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b){state.page=+b.dataset.page;render()}});$('#page-size').addEventListener('change',e=>{state.perPage=+e.target.value;state.page=1;render()});$('#reset').onclick=()=>{state={q:'',status:'',filter:'all',page:1,perPage:state.perPage};$('#query').value='';$('#visit-status').value='';loadPatients(render)};patientListSkeleton();setTimeout(render,520);
